/**
 * Return the id of the location targeted by the event
 * @param  {Event} event Occured event
 * @return {String}      Id of the location
 */
export function getLocationId(event) {
    return event.target.id;
}

/**
 * Return the name of the location targeted by the event
 * @param  {Event} event Occured event
 * @return {String}      Name of the location
 */
export function getLocationName(event) {
    return event.target.attributes.name.value;
}

/**
 * Indicate if the location targeted by the event is selected
 * @param  {Event} event Occured event
 * @return {Boolean}     Is the location selected
 */
export function getLocationSelected(event) {
    return event.target.attributes['aria:checked'].value === 'true';
}

export const locationMap = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY"
};

export const universityList = [
    'Adelphi University',
    'Alliant International University',
    'American International College',
    'American University',
    'Andrews University',
    'Argosy University',
    'Arizona State University--Tempe',
    'Ashland University',
    'Auburn University',
    'Augusta University',
    'Azusa Pacific University',
    'Ball State University',
    'Barry University',
    'Baylor University',
    'Benedictine University',
    'Binghamton University--SUNY',
    'Biola University',
    'Boise State University',
    'Boston College',
    'Boston University',
    'Bowling Green State University',
    'Brandeis University',
    'Brigham Young University--Provo',
    'Brown University',
    'California Institute of Integral Studies',
    'California Institute of Technology',
    'California State University--Fresno',
    'California State University--Fullerton',
    'Capella University',
    'Cardinal Stritch University',
    'Carnegie Mellon University',
    'Case Western Reserve University',
    'Central Michigan University',
    'Clark Atlanta University',
    'Clark University',
    'Clarkson University',
    'Clemson University',
    'Cleveland State University',
    'College of William and Mary',
    'Colorado School of Mines',
    'Colorado State University',
    'Columbia University',
    'Cornell University',
    'Dallas Baptist University',
    'Dartmouth College',
    'DePaul University',
    'Drexel University',
    'Duke University',
    'Duquesne University',
    'East Carolina University',
    'East Tennessee State University',
    'Eastern Michigan University',
    'Edgewood College',
    'Emory University',
    'Florida A&M University',
    'Florida Atlantic University',
    'Florida Institute of Technology',
    'Florida International University',
    'Florida State University',
    'Fordham University',
    'Gardner-Webb University',
    'George Mason University',
    'George Washington University',
    'Georgetown University',
    'Georgia Institute of Technology',
    'Georgia Southern University',
    'Georgia State University',
    'Grand Canyon University',
    'Harvard University',
    'Hofstra University',
    'Howard University',
    'Idaho State University',
    'Illinois Institute of Technology',
    'Illinois State University',
    'Immaculata University',
    'Indiana State University',
    'Indiana University of Pennsylvania',
    'Indiana University--Bloomington',
    'Indiana University-Purdue University--Indianapolis',
    'Iowa State University',
    'Jackson State University',
    'Johns Hopkins University',
    'Kansas State University',
    'Kennesaw State University',
    'Kent State University',
    'Lamar University',
    'Lehigh University',
    'Lesley University',
    'Liberty University',
    'Lindenwood University',
    'Lipscomb University',
    'Louisiana State University--Baton Rouge',
    'Louisiana Tech University',
    'Loyola University Chicago',
    'Marquette University',
    'Maryville University of St. Louis',
    'Massachusetts Institute of Technology',
    'Mercer University',
    'Miami University--Oxford',
    'Michigan State University',
    'Michigan Technological University',
    'Middle Tennessee State University',
    'Mississippi State University',
    'Missouri University of Science & Technology',
    'Montana State University',
    'Montclair State University',
    'Morgan State University',
    'National Louis University',
    'New Jersey Institute of Technology',
    'New Mexico State University',
    'New York University',
    'North Carolina A&T State University',
    'North Carolina State University--Raleigh',
    'North Dakota State University',
    'Northcentral University',
    'Northeastern University',
    'Northern Arizona University',
    'Northern Illinois University',
    'Northwestern University',
    'Nova Southeastern University',
    'Oakland University',
    'Ohio State University--Columbus',
    'Ohio University',
    'Oklahoma State University',
    'Old Dominion University',
    'Oregon State University',
    'Pace University',
    'Pennsylvania State University--University Park',
    'Pepperdine University',
    'Portland State University',
    'Prairie View A&M University',
    'Princeton University',
    'Purdue University--West Lafayette',
    'Regent University',
    'Rensselaer Polytechnic Institute',
    'Rice University',
    'Robert Morris University',
    'Rochester Institute of Technology',
    'Rowan University',
    'Rutgers University--New Brunswick',
    'Rutgers University--Newark',
    'Saint Louis University',
    'Sam Houston State University',
    'San Diego State University',
    'San Francisco State University',
    'Seattle Pacific University',
    'Seton Hall University',
    'Shenandoah University',
    'South Dakota State University',
    'Southern Illinois University--Carbondale',
    'Southern Methodist University',
    'Spalding University',
    'St. John Fisher College',
    'St. John\'s University',
    'Stanford University',
    'Stevens Institute of Technology',
    'Stony Brook University--SUNY',
    'Suffolk University',
    'SUNY College of Environmental Science and Forestry',
    'Syracuse University',
    'Temple University',
    'Tennessee State University',
    'Tennessee Technological University',
    'Texas A&M University--College Station',
    'Texas A&M University--Commerce',
    'Texas A&M University--Corpus Christi',
    'Texas A&M University--Kingsville',
    'Texas Christian University',
    'Texas Southern University',
    'Texas State University',
    'Texas Tech University',
    'Texas Woman\'s University',
    'The Catholic University of America',
    'The New School',
    'Trevecca Nazarene University',
    'Trident University International',
    'Trinity International University',
    'Tufts University',
    'Tulane University',
    'Union Institute and University',
    'Union University',
    'University at Albany--SUNY',
    'University at Buffalo--SUNY',
    'University of Akron',
    'University of Alabama',
    'University of Alabama--Birmingham',
    'University of Alabama--Huntsville',
    'University of Alaska--Fairbanks',
    'University of Arizona',
    'University of Arkansas',
    'University of Arkansas--Little Rock',
    'University of California--Berkeley',
    'University of California--Davis',
    'University of California--Irvine',
    'University of California--Los Angeles',
    'University of California--Merced',
    'University of California--Riverside',
    'University of California--San Diego',
    'University of California--Santa Barbara',
    'University of California--Santa Cruz',
    'University of Central Florida',
    'University of Chicago',
    'University of Cincinnati',
    'University of Colorado--Boulder',
    'University of Colorado--Denver',
    'University of Connecticut',
    'University of Dayton',
    'University of Delaware',
    'University of Denver',
    'University of Florida',
    'University of Georgia',
    'University of Hartford',
    'University of Hawaii--Manoa',
    'University of Houston',
    'University of Idaho',
    'University of Illinois--Chicago',
    'University of Illinois--Urbana-Champaign',
    'University of Iowa',
    'University of Kansas',
    'University of Kentucky',
    'University of La Verne',
    'University of Louisiana--Lafayette',
    'University of Louisiana--Monroe',
    'University of Louisville',
    'University of Maine',
    'University of Maryland--Baltimore County',
    'University of Maryland--College Park',
    'University of Maryland--Eastern Shore',
    'University of Massachusetts--Amherst',
    'University of Massachusetts--Boston',
    'University of Massachusetts--Dartmouth',
    'University of Massachusetts--Lowell',
    'University of Memphis',
    'University of Miami',
    'University of Michigan--Ann Arbor',
    'University of Minnesota--Twin Cities',
    'University of Mississippi',
    'University of Missouri',
    'University of Missouri--Kansas City',
    'University of Missouri--St. Louis',
    'University of Montana',
    'University of Nebraska--Lincoln',
    'University of Nebraska--Omaha',
    'University of Nevada--Las Vegas',
    'University of Nevada--Reno',
    'University of New Hampshire',
    'University of New Mexico',
    'University of New Orleans',
    'University of North Carolina--Chapel Hill',
    'University of North Carolina--Charlotte',
    'University of North Carolina--Greensboro',
    'University of North Dakota',
    'University of North Texas',
    'University of Northern Colorado',
    'University of Notre Dame',
    'University of Oklahoma',
    'University of Oregon',
    'University of Pennsylvania',
    'University of Phoenix',
    'University of Pittsburgh',
    'University of Rhode Island',
    'University of Rochester',
    'University of San Diego',
    'University of San Francisco',
    'University of South Alabama',
    'University of South Carolina',
    'University of South Dakota',
    'University of South Florida',
    'University of Southern California',
    'University of Southern Mississippi',
    'University of St. Thomas',
    'University of Tennessee',
    'University of Texas--Arlington',
    'University of Texas--Austin',
    'University of Texas--Dallas',
    'University of Texas--El Paso',
    'University of Texas--Rio Grande Valley',
    'University of Texas--San Antonio',
    'University of the Cumberlands',
    'University of the Pacific',
    'University of Toledo',
    'University of Tulsa',
    'University of Utah',
    'University of Vermont',
    'University of Virginia',
    'University of Washington',
    'University of West Florida',
    'University of West Georgia',
    'University of Wisconsin--Madison',
    'University of Wisconsin--Milwaukee',
    'University of Wyoming',
    'Utah State University',
    'Valdosta State University',
    'Vanderbilt University',
    'Villanova University',
    'Virginia Commonwealth University',
    'Virginia Tech',
    'Wake Forest University',
    'Walden University',
    'Washington State University',
    'Washington University in St. Louis',
    'Wayne State University',
    'West Virginia University',
    'Western Michigan University',
    'Wichita State University',
    'Widener University',
    'Wilmington University',
    'Worcester Polytechnic Institute',
    'Wright State University',
    'Yale University',
    'Yeshiva University'
]